// <auto-generated />
using System;
using CruiseApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CruiseApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315192129_AddCabinLayouts")]
    partial class AddCabinLayouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CruiseApp.Data.Models.Cabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Cabin.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinType")
                        .HasColumnType("int")
                        .HasComment("Defines type of the Cabin.");

                    b.Property<int>("DeckId")
                        .HasColumnType("int")
                        .HasComment("The Deck of the Cabin.");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("Cabins", t =>
                        {
                            t.HasComment("Represents Cabin of Deck of Ship in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.CabinLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Cabin layout.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinId")
                        .HasColumnType("int")
                        .HasComment("The Cabin.");

                    b.Property<int>("DeckId")
                        .HasColumnType("int")
                        .HasComment("The Deck of the Cabin.");

                    b.Property<int>("PosX")
                        .HasColumnType("int")
                        .HasComment("X coordinate in pixels relative to the top-left corner of the deck image.");

                    b.Property<int>("PosY")
                        .HasColumnType("int")
                        .HasComment("Y coordinate in pixels relative to the top-left corner of the deck image.");

                    b.HasKey("Id");

                    b.HasIndex("CabinId")
                        .IsUnique();

                    b.HasIndex("DeckId", "CabinId")
                        .IsUnique();

                    b.HasIndex("DeckId", "PosX", "PosY")
                        .IsUnique();

                    b.ToTable("CabinLayouts", t =>
                        {
                            t.HasComment("Represents Cabin layout of Deck of Ship in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.CabinReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the CabinReservation.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinId")
                        .HasColumnType("int")
                        .HasComment("CabinId");

                    b.Property<int>("CabinType")
                        .HasColumnType("int")
                        .HasComment("Cabin type at the time of reservation (snapshot)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("CreatedOn");

                    b.Property<int>("CruiseId")
                        .HasColumnType("int")
                        .HasComment("CruiseId");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the reservation has been paid");

                    b.Property<int>("PassengersCount")
                        .HasColumnType("int")
                        .HasComment("Numbers of the passengers in the cabin");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The amount paid for this reservation");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("ReservationStatus");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("UserId");

                    b.HasIndex("CruiseId", "CabinId", "UserId")
                        .IsUnique();

                    b.ToTable("CabinReservations", t =>
                        {
                            t.HasComment("Represents CabinReservation");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Cruise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Optional cruise description");

                    b.Property<DateOnly>("FirstDay")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LastDay")
                        .HasColumnType("date");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Cruises", t =>
                        {
                            t.HasComment("Represents cruise in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.CruiseLike", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User who liked the cruise.");

                    b.Property<int>("CruiseId")
                        .HasColumnType("int")
                        .HasComment("Cruise which is liked from the user.");

                    b.HasKey("UserId", "CruiseId");

                    b.HasIndex("CruiseId");

                    b.ToTable("CruiseLikes", t =>
                        {
                            t.HasComment("Represents likes for a cruise.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for Deck.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeckPlanImage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasComment("Numeric identifier of the Deck.");

                    b.Property<int>("ShipId")
                        .HasColumnType("int")
                        .HasComment("The Ship of the Deck.");

                    b.HasKey("Id");

                    b.HasIndex("ShipId", "Number")
                        .IsUnique();

                    b.ToTable("Decks", t =>
                        {
                            t.HasComment("Represents Deck of the Ship in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Passenger.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasComment("Date of Birth of the Passenger");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Gender of the Passenger");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Nationality of the Passenger");

                    b.Property<DateOnly>("PassportExpirationDate")
                        .HasColumnType("date")
                        .HasComment("Passport Exparation Date of the Passenger");

                    b.Property<string>("PassportIssuingCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Passport Issuing Country of the Passenger");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Passport Number of the Passenger");

                    b.HasKey("Id");

                    b.ToTable("Passengers", t =>
                        {
                            t.HasComment("Represents CHECK-IN DATA");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Point.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSea")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the Point is at sea.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasComment("Name of the Point.");

                    b.HasKey("Id");

                    b.ToTable("Points", t =>
                        {
                            t.HasComment("Represent Point in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.ReservationPassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the ReservationPassenger.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinReservationId")
                        .HasColumnType("int")
                        .HasComment("CabinReservationId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("First Name of the Passenger");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Last Name of the Passenger");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasComment("Id of the Passenger");

                    b.Property<int>("PassengerOrder")
                        .HasColumnType("int")
                        .HasComment("Order of the assenger in the cabin");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("CabinReservationId", "PassengerOrder")
                        .IsUnique();

                    b.ToTable("ReservationPassengers", t =>
                        {
                            t.HasComment("Represents ReservationPassenger");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for Route.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShipId")
                        .HasColumnType("int")
                        .HasComment("The Ship of the Route.");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Routes", t =>
                        {
                            t.HasComment("Represents Route in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.RouteDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for RouteDay.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE")
                        .HasComment("Calendar date of the RouteDay.");

                    b.Property<int>("PointId")
                        .HasColumnType("int")
                        .HasComment("The Point of the RouteDay.");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasComment("The Route of the RouteDay.");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("RouteId", "Date")
                        .IsUnique();

                    b.ToTable("RouteDays", t =>
                        {
                            t.HasComment("Represents RouteDay in the system.");
                        });
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Ship.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("Name of the Ship.");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ships", t =>
                        {
                            t.HasComment("Represent ship in the system.");
                        });
                });

            modelBuilder.Entity("CruiseCabinPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the CabinCruisePrice.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinType")
                        .HasColumnType("int")
                        .HasComment("Type of the Cabin");

                    b.Property<int>("CruiseId")
                        .HasColumnType("int")
                        .HasComment("Cruise for which this price applies");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price for the cabin type on this cruise");

                    b.HasKey("Id");

                    b.HasIndex("CruiseId", "CabinType")
                        .IsUnique();

                    b.ToTable("CruiseCabinPrices");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Cabin", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Deck", "Deck")
                        .WithMany("Cabins")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.CabinLayout", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Cabin", "Cabin")
                        .WithOne("Layout")
                        .HasForeignKey("CruiseApp.Data.Models.CabinLayout", "CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CruiseApp.Data.Models.Deck", "Deck")
                        .WithMany("CabinLayouts")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.CabinReservation", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Cabin", "Cabin")
                        .WithMany()
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CruiseApp.Data.Models.Cruise", "Cruise")
                        .WithMany()
                        .HasForeignKey("CruiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("Cruise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Cruise", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.CruiseLike", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Cruise", "Cruise")
                        .WithMany()
                        .HasForeignKey("CruiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cruise");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Deck", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Ship", "Ship")
                        .WithMany("Decks")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.ReservationPassenger", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.CabinReservation", "CabinReservation")
                        .WithMany()
                        .HasForeignKey("CabinReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CruiseApp.Data.Models.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinReservation");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Route", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Ship", "Ship")
                        .WithOne()
                        .HasForeignKey("CruiseApp.Data.Models.Route", "ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.RouteDay", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CruiseApp.Data.Models.Route", "Route")
                        .WithMany("Days")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CruiseCabinPrice", b =>
                {
                    b.HasOne("CruiseApp.Data.Models.Cruise", "Cruise")
                        .WithMany("CabinPrices")
                        .HasForeignKey("CruiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cruise");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Cabin", b =>
                {
                    b.Navigation("Layout");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Cruise", b =>
                {
                    b.Navigation("CabinPrices");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Deck", b =>
                {
                    b.Navigation("CabinLayouts");

                    b.Navigation("Cabins");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Route", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("CruiseApp.Data.Models.Ship", b =>
                {
                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
